"""migration1

Revision ID: d8bd9371d773
Revises: 3f0968d4f6f7
Create Date: 2021-06-13 10:27:44.453877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bd9371d773'
down_revision = '3f0968d4f6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
