"""migration1

Revision ID: f84510da307d
Revises: fa98ccfdcf1b
Create Date: 2021-06-13 12:31:40.369158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84510da307d'
down_revision = 'fa98ccfdcf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
