"""migration1

Revision ID: fa98ccfdcf1b
Revises: d8bd9371d773
Create Date: 2021-06-13 10:35:39.232569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa98ccfdcf1b'
down_revision = 'd8bd9371d773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
